config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  resources :books
  resources :recommends
  resources :contacts
  resources :blogs
  resources :information
  resources :services
  resources :hotel_intros
  resources :abouts
  resources :mains
  resources :enrollments
  devise_for :users
  resources :rooms do 
    resources :reserves, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/book.rb
class Book < ApplicationRecord


    belongs_to :user 
    belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, :description, :address, :phone, :email, :websit, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user, :room, :review, :rating, presence: true

  # validates_presence_of :rating, if: :review?
  # validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :room_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :room_id, scope: :user_id  #user cant be subscribed to the same course twice

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def to_s
    user.to_s + " " + room.to_s
  end
  
end

app/models/hotel_intro.rb
class HotelIntro < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/main.rb
class Main < ApplicationRecord
    validates :first_title, :first_description, :second_title, :second_description, presence: true

    has_one_attached :avatar
end

app/models/recommend.rb
class Recommend < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/reserf.rb
class Reserf < ApplicationRecord
  belongs_to :room
  belongs_to :user


  validates :user, :room, presence: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_uniqueness_of :room_id, scope: :user_id

  def to_s
    user.to_s + " " + room.to_s
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true 
  validates_uniqueness_of :name
end

app/models/room.rb
class Room < ApplicationRecord
    validates :title, :short_description, :size, :view, :bed, :price, :opacity, presence: true
    validates :description, presence: true, length: {:minimum => 5} 

    belongs_to :user 
    has_many :enrollments
    has_many :reserves
    has_one_attached :avatar

    def to_s 
        title
    end
    has_rich_text :description

    extend FriendlyId
    friendly_id :title, use: :slugged
    # friendly_id :generated_slug, use: :slugged
    # def generated_slug
    #     require 'securerandom'
    #     @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
    # end

    # def to_s 
    #     slug 
    # end
    BEDS = [:"1", :"2", :"3", :"4"]
    def self.beds 
        BEDS.map{|bed| [bed, bed]}
    end

    OPACITYS = [:"1", :"2", :"3", :"4", :"5", :"6"]
    def self.opacitys 
        OPACITYS.map{|opacity| [opacity, opacity]}
    end

    include PublicActivity::Model
    tracked owner: Proc.new{|controller, model| controller.current_user}

    def book(user)
        self.reserves.where(user_id: [user.id], room_id: [self.id].empty? )
    end
end

app/models/service.rb
class Service < ApplicationRecord
    validates :title, :description, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  rolify

  has_many :reserves
  has_many :rooms
  has_many :enrollments
  
  def to_s 
    email 
  end


  extend FriendlyId
  friendly_id :email, use: :slugged

  def username
    self.email.split(/@/).first
  end

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:costumer)
    else 
      self.add_role(:costumer)
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago 
  end
  
  def book_room(room)
    self.reserves.create(room: room)
  end

  private 
  def must_have_a_role 
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end
end

app/controllers/hotel_intros_controller.rb
class HotelIntrosController < ApplicationController
  before_action :set_hotel_intro, only: %i[ show edit update destroy ]

  # GET /hotel_intros or /hotel_intros.json
  def index
    @hotel_intros = HotelIntro.all
  end

  # GET /hotel_intros/1 or /hotel_intros/1.json
  def show
  end

  # GET /hotel_intros/new
  def new
    @hotel_intro = HotelIntro.new
  end

  # GET /hotel_intros/1/edit
  def edit
  end

  # POST /hotel_intros or /hotel_intros.json
  def create
    @hotel_intro = HotelIntro.new(hotel_intro_params)

    respond_to do |format|
      if @hotel_intro.save
        format.html { redirect_to hotel_intro_url(@hotel_intro), notice: "Hotel intro was successfully created." }
        format.json { render :show, status: :created, location: @hotel_intro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel_intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotel_intros/1 or /hotel_intros/1.json
  def update
    respond_to do |format|
      if @hotel_intro.update(hotel_intro_params)
        format.html { redirect_to hotel_intro_url(@hotel_intro), notice: "Hotel intro was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel_intro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel_intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_intros/1 or /hotel_intros/1.json
  def destroy
    @hotel_intro.destroy

    respond_to do |format|
      format.html { redirect_to hotel_intros_url, notice: "Hotel intro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_intro
      @hotel_intro = HotelIntro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_intro_params
      params.require(:hotel_intro).permit(:title, :description, :avatar)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotel_intros_helper.rb
module HotelIntrosHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

    def review_button(room)
        user_room = room.enrollments.where(user: current_user)
        if current_user
            if user_room.any?
                if user_room.pending_review.any?
                    link_to 'Add a review', edit_enrollment_path(user_room.first)
                else 
                    link_to 'Review', enrollment_path(user_room.first)
                end
            end
        end
    end


    def reserve_button(room)
        user_room = room.reserves.where(user: current_user)
        if current_user
            if room.reserves.where(user: current_user).any?
                "You Booked this room."
                link_to "For more convenience Complete your information.", edit_reserf_path(user_room.first), class: "btn btn-md btn-danger"
            else
                link_to "Book #{number_to_currency(room.price)} Per night ", new_room_reserf_path(room), class: "btn btn-md btn-success"
            end
        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/hotel_intros/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@hotel_intro) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.file_field :avatar
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/hotel_intros/_hotel.html.haml
.col-md-4
  %section.ftco-section.ftco-services
    .container
      .row
        .d-flex.services.align-self-stretch.px-4.ftco-animate
          .d-block.services-wrap.text-center
            .media-body.py-4.px-3
              - if hotel_intro.avatar.attached?
                = image_tag hotel_intro.avatar, width: "100%";
              %h2.heading
                = hotel_intro.title
              %p 
                = hotel_intro.description 
              

                    
              %p
              - if current_user
                - if current_user.has_role?(:admin)
                  = link_to 'Edit', edit_hotel_intro_path(hotel_intro), class: 'btn btn-sm btn-warning'
                  = link_to 'Destroy', hotel_intro, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/hotel_intros/edit.html.haml
.container 
    .card 
        .card-header
            %h1 Editing hotel_intro
        .card-body
            = render 'form'
        .card-footer
            = link_to 'Show', @hotel_intro
            \|
            = link_to 'Back', hotel_intros_path

app/views/hotel_intros/index.html.haml
.container
  %br
  - @hotel_intros.each do |hotel_intro|
    = render 'hotel_intros/hotel', hotel_intro: hotel_intro

  = link_to 'New Hotel intro', new_hotel_intro_path, class: 'btn btn-sm btn-primary'

app/views/hotel_intros/new.html.haml
.container 
    .card 
        .card-header
            %h1 New hotel_intro
        .card-body
            = render 'form'
        .card-footer
            = link_to 'Back', hotel_intros_path

app/views/hotel_intros/show.html.haml
.container 
  .card 
    .card-header
      %h1
        = @hotel_intro.title
    .card-body
      %p
        %b Description:
        = @hotel_intro.description
    .card-footer
      = link_to 'Edit', edit_hotel_intro_path(@hotel_intro)
      \|
      = link_to 'Back', hotel_intros_path