config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  resources :books
  resources :recommends
  resources :contacts
  resources :blogs
  resources :information
  resources :services
  resources :hotel_intros
  resources :abouts
  resources :mains
  resources :enrollments
  devise_for :users
  resources :rooms do 
    resources :reserves, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/book.rb
class Book < ApplicationRecord


    belongs_to :user 
    belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, :description, :address, :phone, :email, :websit, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user, :room, :review, :rating, presence: true

  # validates_presence_of :rating, if: :review?
  # validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :room_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :room_id, scope: :user_id  #user cant be subscribed to the same course twice

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def to_s
    user.to_s + " " + room.to_s
  end
  
end

app/models/hotel_intro.rb
class HotelIntro < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/main.rb
class Main < ApplicationRecord
    validates :first_title, :first_description, :second_title, :second_description, presence: true

    has_one_attached :avatar
end

app/models/recommend.rb
class Recommend < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/reserf.rb
class Reserf < ApplicationRecord
  belongs_to :room
  belongs_to :user


  validates :user, :room, presence: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_uniqueness_of :room_id, scope: :user_id

  def to_s
    user.to_s + " " + room.to_s
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true 
  validates_uniqueness_of :name
end

app/models/room.rb
class Room < ApplicationRecord
    validates :title, :short_description, :size, :view, :bed, :price, :opacity, presence: true
    validates :description, presence: true, length: {:minimum => 5} 

    belongs_to :user 
    has_many :enrollments
    has_many :reserves
    has_one_attached :avatar

    def to_s 
        title
    end
    has_rich_text :description

    extend FriendlyId
    friendly_id :title, use: :slugged
    # friendly_id :generated_slug, use: :slugged
    # def generated_slug
    #     require 'securerandom'
    #     @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
    # end

    # def to_s 
    #     slug 
    # end
    BEDS = [:"1", :"2", :"3", :"4"]
    def self.beds 
        BEDS.map{|bed| [bed, bed]}
    end

    OPACITYS = [:"1", :"2", :"3", :"4", :"5", :"6"]
    def self.opacitys 
        OPACITYS.map{|opacity| [opacity, opacity]}
    end

    include PublicActivity::Model
    tracked owner: Proc.new{|controller, model| controller.current_user}

    def book(user)
        self.reserves.where(user_id: [user.id], room_id: [self.id].empty? )
    end
end

app/models/service.rb
class Service < ApplicationRecord
    validates :title, :description, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  rolify

  has_many :reserves
  has_many :rooms
  has_many :enrollments
  
  def to_s 
    email 
  end


  extend FriendlyId
  friendly_id :email, use: :slugged

  def username
    self.email.split(/@/).first
  end

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:costumer)
    else 
      self.add_role(:costumer)
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago 
  end
  
  def book_room(room)
    self.reserves.create(room: room)
  end

  private 
  def must_have_a_role 
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @blogs = Blog.all.limit(3)
    @rooms = Room.all.limit(3)
    @hotel_intros = HotelIntro.all.limit(3)
    @services = Service.all
    @main = Main.find(1)
    @recommend = Recommend.find(1)
  end

  def activity
    @activities = PublicActivity::Activity.all
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

    def review_button(room)
        user_room = room.enrollments.where(user: current_user)
        if current_user
            if user_room.any?
                if user_room.pending_review.any?
                    link_to 'Add a review', edit_enrollment_path(user_room.first)
                else 
                    link_to 'Review', enrollment_path(user_room.first)
                end
            end
        end
    end


    def reserve_button(room)
        user_room = room.reserves.where(user: current_user)
        if current_user
            if room.reserves.where(user: current_user).any?
                "You Booked this room."
                link_to "For more convenience Complete your information.", edit_reserf_path(user_room.first), class: "btn btn-md btn-danger"
            else
                link_to "Book #{number_to_currency(room.price)} Per night ", new_room_reserf_path(room), class: "btn btn-md btn-success"
            end
        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/home/activity.html.haml
- content_for :title do 
    Hotel
    \|
    Activity

%h3
    .text-center
        Activity 
        .badge.badge-info 
            = @activities.count
%p
%ul.list-group
    - @activities.each do |activity|
        %li.list-group-item
            = activity.id 
            = activity.trackable_type
            = activity.trackable_id
            = link_to activity.trackable, activity.trackable
            = activity.key
            = activity.parameters 
            = activity.owner

app/views/home/index.html.haml
.hero-wrap.js-fullheight{"data-stellar-background-ratio" => "0.5", style: "margin-bottom: -100px; background-image: url('http://127.0.0.1:3000#{url_for(@main.avatar)}');"}
  -# = image_tag @main.avatar, width: "100%";
  .overlay
  .container
    .row.no-gutters.slider-text.js-fullheight.align-items-center.justify-content-start{"data-scrollax-parent" => "true"}
      .col-md-7
        %h2.subheading 
          = @main.first_title
        %h1.mb-4 
          = @main.first_description

-# %section.ftco-section.ftco-book.ftco-no-pt.ftco-no-pb
-#   .container
-#     .row.justify-content-end
-#       .col-lg-4
-#         %form.appointment-form{action: "#"}
-#           %h3.mb-3 Book your apartment
-#           .row
-#             .col-md-12
-#               .form-group
-#                 %input.form-control{placeholder: "Full Name", type: "text"}/
-#             .col-md-6
-#               .form-group
-#                 .input-wrap
-#                   .icon
-#                     %span.ion-md-calendar
-#                   %input.form-control.appointment_date-check-in{placeholder: "Check-In", type: "text"}/
-#             .col-md-6
-#               .form-group
-#                 .input-wrap
-#                   .icon
-#                     %span.ion-md-calendar
-#                   %input.form-control.appointment_date-check-out{placeholder: "Check-Out", type: "text"}/
-#             .col-md-6
-#               .form-group
-#                 .form-field
-#                   .select-wrap
-#                     %select.form-control{id: "", name: ""}
-#                       %option{value: ""} Adults
-#                       %option{value: ""} 1
-#                       %option{value: ""} 2
-#                       %option{value: ""} 3
-#                       %option{value: ""} 4
-#                       %option{value: ""} 5
-#             .col-md-6
-#               .form-group
-#                 .form-field
-#                   .select-wrap
-#                     %select.form-control{id: "", name: ""}
-#                       %option{value: ""} Children
-#                       %option{value: ""} 1
-#                       %option{value: ""} 2
-#                       %option{value: ""} 3
-#                       %option{value: ""} 4
-#                       %option{value: ""} 5
-#             .col-md-6
-#               .form-group
-#                 %input.form-control{placeholder: "Phone number", type: "text"}/
-#             .col-md-6
-#               .form-group
-#                 .input-wrap
-#                   .icon
-#                     %span.ion-ios-clock
-#                   %input.form-control.appointment_time{placeholder: "Time", type: "text"}/
-#             .col-md-12
-#               .form-group
-#                 %input.btn.btn-primary.py-3.px-4{type: "submit", value: "Book Appartment Now"}/
.container
  - @rooms.each do |room|
    = render 'rooms/room', room: room
  

.row
%section.ftco-intro{"data-stellar-background-ratio" => "0.5", style: "background-image: url('http://127.0.0.1:3000#{url_for(@main.avatar)}');"}
  .overlay
  .container
    .row.justify-content-center
      .col-md-9.text-center
        %h2 
          = @main.second_title
        %p.mb-4 
          = @main.second_description
        %p.mb-0
.p
.container
  - @hotel_intros.each do |hotel_intro|
    = render 'hotel_intros/hotel', hotel_intro: hotel_intro

%section.bg-light
  .container
    .row
      .col-md-6.wrap-about
        = image_tag @recommend.avatar, width: "100%";
        %h2 
          = @recommend.title
        %p 
          = @recommend.description
        - if current_user
          - if current_user.has_role?(:admin)
            = link_to 'Edit', edit_recommend_path(@recommend), class: 'btn btn-lm btn-warning'
        
      .col-md-6.wrap-about.ftco-animate
        .heading-section
          .pl-md-5
            %h2.mb-2 What we offer
        .pl-md-5
          %p A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.
          .row
            - @services.each do |service|
              .services-2.col-md-3.d-flex.w-50
                .icon.d-flex.justify-content-center.align-items-center
                  %span{class: "#{service.icon}"}
                .media-body.pl-3
                  %h3.heading 
                    = service.title
                  %p 
                    = service.description
                  - if current_user
                    - if current_user.has_role?(:admin)
                      = link_to 'Edit', edit_service_path(service), class: 'btn btn-sm btn-warning'
                      = link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
            
    .text-center
      .blog-news
        %h1
          Latest news from our blog
        .subheading 
          = link_to "News & Blog", blogs_path
          

.row
.container
  - @blogs.each do |blog|
    = render 'blogs/blog', blog: blog
.row