config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  resources :books
  resources :recommends
  resources :contacts
  resources :blogs
  resources :information
  resources :services
  resources :hotel_intros
  resources :abouts
  resources :mains
  resources :enrollments
  devise_for :users
  resources :rooms do 
    resources :reserves, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/book.rb
class Book < ApplicationRecord


    belongs_to :user 
    belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, :description, :address, :phone, :email, :websit, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user, :room, :review, :rating, presence: true

  # validates_presence_of :rating, if: :review?
  # validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :room_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :room_id, scope: :user_id  #user cant be subscribed to the same course twice

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def to_s
    user.to_s + " " + room.to_s
  end
  
end

app/models/hotel_intro.rb
class HotelIntro < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/main.rb
class Main < ApplicationRecord
    validates :first_title, :first_description, :second_title, :second_description, presence: true

    has_one_attached :avatar
end

app/models/recommend.rb
class Recommend < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/reserf.rb
class Reserf < ApplicationRecord
  belongs_to :room
  belongs_to :user


  validates :user, :room, presence: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_uniqueness_of :room_id, scope: :user_id

  def to_s
    user.to_s + " " + room.to_s
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true 
  validates_uniqueness_of :name
end

app/models/room.rb
class Room < ApplicationRecord
    validates :title, :short_description, :size, :view, :bed, :price, :opacity, presence: true
    validates :description, presence: true, length: {:minimum => 5} 

    belongs_to :user 
    has_many :enrollments
    has_many :reserves
    has_one_attached :avatar

    def to_s 
        title
    end
    has_rich_text :description

    extend FriendlyId
    friendly_id :title, use: :slugged
    # friendly_id :generated_slug, use: :slugged
    # def generated_slug
    #     require 'securerandom'
    #     @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
    # end

    # def to_s 
    #     slug 
    # end
    BEDS = [:"1", :"2", :"3", :"4"]
    def self.beds 
        BEDS.map{|bed| [bed, bed]}
    end

    OPACITYS = [:"1", :"2", :"3", :"4", :"5", :"6"]
    def self.opacitys 
        OPACITYS.map{|opacity| [opacity, opacity]}
    end

    include PublicActivity::Model
    tracked owner: Proc.new{|controller, model| controller.current_user}

    def book(user)
        self.reserves.where(user_id: [user.id], room_id: [self.id].empty? )
    end
end

app/models/service.rb
class Service < ApplicationRecord
    validates :title, :description, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  rolify

  has_many :reserves
  has_many :rooms
  has_many :enrollments
  
  def to_s 
    email 
  end


  extend FriendlyId
  friendly_id :email, use: :slugged

  def username
    self.email.split(/@/).first
  end

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:costumer)
    else 
      self.add_role(:costumer)
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago 
  end
  
  def book_room(room)
    self.reserves.create(room: room)
  end

  private 
  def must_have_a_role 
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  def index
    # @enrollments = Enrollment.all
    # @pagy, @enrollments = pagy(Enrollment.all)

    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))

    authorize @enrollments
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.user = current_user
  
    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(:room_id, :rating, :review)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

    def review_button(room)
        user_room = room.enrollments.where(user: current_user)
        if current_user
            if user_room.any?
                if user_room.pending_review.any?
                    link_to 'Add a review', edit_enrollment_path(user_room.first)
                else 
                    link_to 'Review', enrollment_path(user_room.first)
                end
            end
        end
    end


    def reserve_button(room)
        user_room = room.reserves.where(user: current_user)
        if current_user
            if room.reserves.where(user: current_user).any?
                "You Booked this room."
                link_to "For more convenience Complete your information.", edit_reserf_path(user_room.first), class: "btn btn-md btn-danger"
            else
                link_to "Book #{number_to_currency(room.price)} Per night ", new_room_reserf_path(room), class: "btn btn-md btn-success"
            end
        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/enrollments/_enrollment.html.haml
.card 
    .card-header 
        .fa.fa-user 
        = link_to enrollment.user.username, user_path(enrollment.user)
        .fa.fa-clock 
        = time_ago_in_words(enrollment.updated_at)
        .fa.fa-door-closed
        = link_to enrollment.room, room_path(enrollment.room)
    .card-body 
        .text-warning.fa.fa-star
        %b= enrollment.rating
        .row
        .fa.fa-comment 
        %small= enrollment.review 
    - if current_user
        .card-footer 
            - if policy(enrollment).edit?
                = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :room
    = f.input :rating, collection: 1..5
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title do 
    Hotel
    \|
    Editing
    = @enrollment
.container
    .card 
        .card-header 
            %h1 
                .text-warning.fa.fa-star
                Add a Review
        .card-body
            = render 'form'
        .card-footer
            = link_to 'Show Review', @enrollment
            \|
            = link_to 'Back to Room', room_path(@enrollment.room)

app/views/enrollments/index.html.haml
- content_for :title do 
  Hotel 
  \|
  All Enrollments
.container
  %h3
    .text-center
      Enrollments 
      .badge.badge-info 
        = @enrollments.count
  %p
  .form-inline
    = search_form_for @q, url: @ransack_path do |f|
      = f.search_field :user_email_cont, placeholder: "user email"
      = f.search_field :room_title_cont, placeholder: "room title"
      = f.search_field :rating_eq, placeholder: "rating"
      = f.search_field :review_cont, placeholder: "review"
      = f.submit
      = link_to @ransack_path, class: 'btn btn-sm btn-primary' do 
        .fa.fa-sync
  %br
  .table-responsive
    %table.table.table-bordered.table-striped.table-sm
      %thead
        %tr
          %th ID
          %th
            = sort_link(@q, :user_email)
          %th 
            = sort_link(@q, :created_at)
          %th 
            = sort_link(@q, :room_title)
          %th 
            .text-warning.fa.fa-clock
            Reviewed on
          %th 
            = sort_link(@q, :rating)
            .text-warning.fa.fa-star
          %th 
            .text-warning.fa.fa-comment
            Review
          %th
          %th
          %th

      %tbody
        - @enrollments.each do |enrollment|
          %tr
            %td= enrollment.id
            %td= link_to enrollment.user, user_path(enrollment.user)
            %td= enrollment.created_at.strftime("%d/%b/%Y - %H:%M")
            %td= link_to enrollment.room, room_path(enrollment.room)
            %td
              - if enrollment.rating.present?
                = enrollment.updated_at.strftime("%d/%b/%Y - %H:%M")
            %td= enrollment.rating
            %td= enrollment.review
            %td
              %small= link_to 'See Review', enrollment
            %td
              %small= link_to 'Add Review', edit_enrollment_path(enrollment)
            %td
              %small= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'New Enrollment', new_enrollment_path
  %p
    -# != pagy_nav(@pagy)
    -# != pagy_bootstrap_nav(@pagy)
    -# != pagy_bootstrap_nav_js(@pagy)
    != pagy_bootstrap_combo_nav_js(@pagy)

app/views/enrollments/new.html.haml
- content_for :title do 
    Hotel
    \|
    New enrollment
.container
    .card 
        .card-header 
            %h1 
                .fa.fa-lock-open
                New enrollment
        .card-body
            = render 'form'
        .card-footer
            = link_to 'Back', enrollments_path

app/views/enrollments/show.html.haml
.container
    = render 'enrollments/enrollment', enrollment: @enrollment