config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  resources :books
  resources :recommends
  resources :contacts
  resources :blogs
  resources :information
  resources :services
  resources :hotel_intros
  resources :abouts
  resources :mains
  resources :enrollments
  devise_for :users
  resources :rooms do 
    resources :reserves, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/book.rb
class Book < ApplicationRecord


    belongs_to :user 
    belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, :description, :address, :phone, :email, :websit, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user, :room, :review, :rating, presence: true

  # validates_presence_of :rating, if: :review?
  # validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :room_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :room_id, scope: :user_id  #user cant be subscribed to the same course twice

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def to_s
    user.to_s + " " + room.to_s
  end
  
end

app/models/hotel_intro.rb
class HotelIntro < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/main.rb
class Main < ApplicationRecord
    validates :first_title, :first_description, :second_title, :second_description, presence: true

    has_one_attached :avatar
end

app/models/recommend.rb
class Recommend < ApplicationRecord
    validates :title, :description, presence: true

    has_one_attached :avatar
end

app/models/reserf.rb
class Reserf < ApplicationRecord
  belongs_to :room
  belongs_to :user


  validates :user, :room, presence: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_uniqueness_of :room_id, scope: :user_id

  def to_s
    user.to_s + " " + room.to_s
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true 
  validates_uniqueness_of :name
end

app/models/room.rb
class Room < ApplicationRecord
    validates :title, :short_description, :size, :view, :bed, :price, :opacity, presence: true
    validates :description, presence: true, length: {:minimum => 5} 

    belongs_to :user 
    has_many :enrollments
    has_many :reserves
    has_one_attached :avatar

    def to_s 
        title
    end
    has_rich_text :description

    extend FriendlyId
    friendly_id :title, use: :slugged
    # friendly_id :generated_slug, use: :slugged
    # def generated_slug
    #     require 'securerandom'
    #     @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
    # end

    # def to_s 
    #     slug 
    # end
    BEDS = [:"1", :"2", :"3", :"4"]
    def self.beds 
        BEDS.map{|bed| [bed, bed]}
    end

    OPACITYS = [:"1", :"2", :"3", :"4", :"5", :"6"]
    def self.opacitys 
        OPACITYS.map{|opacity| [opacity, opacity]}
    end

    include PublicActivity::Model
    tracked owner: Proc.new{|controller, model| controller.current_user}

    def book(user)
        self.reserves.where(user_id: [user.id], room_id: [self.id].empty? )
    end
end

app/models/service.rb
class Service < ApplicationRecord
    validates :title, :description, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  rolify

  has_many :reserves
  has_many :rooms
  has_many :enrollments
  
  def to_s 
    email 
  end


  extend FriendlyId
  friendly_id :email, use: :slugged

  def username
    self.email.split(/@/).first
  end

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:costumer)
    else 
      self.add_role(:costumer)
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago 
  end
  
  def book_room(room)
    self.reserves.create(room: room)
  end

  private 
  def must_have_a_role 
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @ransack_rooms = Room.ransack(params[:rooms_search], search_key: :rooms_search)
    # @rooms = @ransack_rooms.result.includes(:user)
    @pagy, @rooms = pagy(@ransack_rooms.result.includes(:user))
  end

  def show
    @enrollment = Enrollment.all
  end

  def new
    @room = Room.new
    authorize @room
  end

  def edit
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    authorize @room
    @room.user = current_user
    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @room
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @room
    @room.destroy
    
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end

    
  end

  private

    def set_room
      @room = Room.friendly.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:title, :description, :short_description, :size, :view, :bed, :price, :opacity, :avatar)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

    def review_button(room)
        user_room = room.enrollments.where(user: current_user)
        if current_user
            if user_room.any?
                if user_room.pending_review.any?
                    link_to 'Add a review', edit_enrollment_path(user_room.first)
                else 
                    link_to 'Review', enrollment_path(user_room.first)
                end
            end
        end
    end


    def reserve_button(room)
        user_room = room.reserves.where(user: current_user)
        if current_user
            if room.reserves.where(user: current_user).any?
                "You Booked this room."
                link_to "For more convenience Complete your information.", edit_reserf_path(user_room.first), class: "btn btn-md btn-danger"
            else
                link_to "Book #{number_to_currency(room.price)} Per night ", new_room_reserf_path(room), class: "btn btn-md btn-success"
            end
        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/rooms/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@room) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.file_field :avatar
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    = f.input :size, collection: ["20", "30", "40", "50"]
    = f.input :view, collection: ["City", "Sea", "Mountain", "Hotel grounds", "No View"]
    = f.input :bed, collection: ["1", "2", "3", "4"] 
    = f.input :price
    = f.input :opacity, collection: ["1", "2", "3", "4", "5", "6"]
  %p
  .form-actions
    = f.button :submit, class: 'btn-sm btn-success'

app/views/rooms/_room.html.haml
.col-md-4
  %section.ftco-section.ftco-services
    .container
      .row
        .d-flex.services.align-self-stretch.px-4.ftco-animate
          .d-block.services-wrap.text-center
            .media-body.py-4.px-3
              - if room.avatar.attached?
                = image_tag room.avatar, width: "100%";
              %h2.heading
                = room.title
              %p 
                = room.short_description  
              %p.text-success
                = number_to_currency(room.price)
                per night
              %h4 
                %b= 'size'.humanize + ":"
                = room.size 
                m2
              %h4   
                %b= 'view'.humanize + ":"
                = room.view 
              %h4   
                .fas.fa-bed
                %b= 'bed'.humanize + ":"
                = room.bed 
              %h4   
                .fa.fa-users
                %b= 'max'.humanize + ":"
                = room.opacity
                Persons
              %p
                = link_to 'Read more', room, class: 'btn btn-primary'
                    
              %p
                - if current_user
                  = link_to 'Edit', edit_room_path(room), class: 'btn btn-sm btn-warning' if policy(room).edit?
                  = link_to 'Destroy', room, method: :delete, data: {confirm: 'Are you sure? '}, class: 'btn btn-sm btn-danger' if policy(room).destroy?

app/views/rooms/edit.html.haml
- content_for :title do 
    Hotel
    \|
    Editing
    = @room.title
.container
    .card 
        .card-header 
            %h1 Editing room
        .card-body
            = render 'form'

    = link_to 'Back', rooms_path
    %p 

app/views/rooms/index.html.haml
- content_for :title do 
  Hotel 
  \|
  All rooms
.container
  %h3
    .text-center
      Rooms 
      .badge.badge-info 
        = @rooms.count

  %p

  .row 
    .col-md-2 
      = search_form_for @ransack_rooms, as: :rooms_search, url: @ransack_path do |f|
    
        = f.label :title
        = f.search_field :title_cont, placeholder: "Title", class: 'form-control form-control-sm'                          # cont => contain
        = f.label :description
        = f.search_field :short_description_cont, placeholder: "Description", class: 'form-control form-control-sm'
        -# = f.search_field :language_cont, placeholder: "Language", class: 'form-control form-control-sm'
        %p
        = f.label :bed
        = f.select :bed_eq, Room.beds, include_blank: true
        -# = f.search_field :level_cont, placeholder: "Level", class: 'form-control form-control-sm'
        %br
        = f.label :opacity
        = f.select :opacity_eq, Room.opacitys, include_blank: true
        %br
        = f.label :view
        = f.search_field :view_cont, placeholder: "View", class: 'form-control form-control-sm' 
        %br
        = f.label :size
        = f.search_field :size_eq, placeholder: "Size", class: 'form-control form-control-sm'
        %br
        = f.label :price
        = f.search_field :price_eq, placeholder: "Price", class: 'form-control form-control-sm'   
        %p
        = f.submit 
      = link_to 'refresh', @ransack_path

    .col-md-10
      - @rooms.in_groups_of(3, false).each do |item|
        .row
          - item.each do |room|
            = render 'rooms/room', room: room
        
    %p
    -# != pagy_nav(@pagy)
    -# != pagy_bootstrap_nav(@pagy)
    -# != pagy_bootstrap_nav_js(@pagy)
    != pagy_bootstrap_combo_nav_js(@pagy)

  %br

app/views/rooms/new.html.haml
- content_for :title do 
    Hotel
    \|
    New room
.container
    .card 
        .card-header 
            %h1 New room
        .card-body
            = render 'form'

    = link_to 'Back', rooms_path

    %p

app/views/rooms/show.html.haml
- content_for :title do 
  Hotel 
  \|
  = @room.title
.container
  = link_to 'Rooms', rooms_path
  \/
  = link_to @room.title, room_path(@room)
  %p

  .col-md-10
    .row

      %h1.heading
        = @room.title
      %h3
        = @room.short_description 
      %h4 
        = @room.description 
      %h4 
        %b= 'size'.humanize + ":"
        = @room.size 
        m2
      %h4  
        %b= 'view'.humanize + ":"
        = @room.view 
      %h4  
        .fas.fa-bed
        %b= 'bed'.humanize + ":"
        = @room.bed 
      %h4  
        .fa.fa-users
        %b= 'max'.humanize + ":"
        = @room.opacity
        Persons

      
      %p 
        .fa.fa-comment 
          -# %small= @enrollment.current_room.review
        -# = enrollment_button(@room)
        -# = @enrollment.where(room_id: @room.id)
        = review_button(@room)
      %p
        - if @room.reserves.where(user: current_user).any?
          %b.text-success
            = "You Booked this room."
      %p
        = reserve_button(@room)
        
                    
      %p
        = link_to 'Edit', edit_room_path(@room), class: 'btn btn-sm btn-warning' if policy(@room).edit?
        = link_to 'Destroy', room_path, method: :delete, data: {confirm: 'Are you sure? '}, class: 'btn btn-sm btn-danger' if policy(@room).destroy?